### PR TITLE
feat: Add release scripts for streamlined release process (#27)

### PR DESCRIPTION
**Pull request by yokuze**
This PR provides a set of scripts and configuration to simplify the version bumping and
CHANGELOG generation process. The process works for both open-source projects hosted on
Github, or closed-source projects hosted on a private hosting instance such as Gitlab.

This lengthy comment is broken into two major sections: 1) An overview of the current process
and an outline of the problems that it has, some of which are solved by this PR. This is
to remind the reviewer of the current process so they can compare it to the new process.
2) Integration and usage instructions for the new scripts.

#### Initial Release Candidate

Here is an outline of the current version-bumping process, starting with the process for
creating the first release candidate for a new version. This process assumes that the
project has a dependency on `standard-version` and an NPM script called "release" defined
as: `"release": "standard-version"`.

1. In the project's root folder, check out a new branch called
   `prep-v${WHAT_YOU_THINK_THE_NEW_VERSION_WILL_BE}`
1. Run `npm run release -- --skip.commit --skip.tag --prerelease=rc`
   * This command calculates the next recommended version and CHANGELOG entries from the
     git log's commit messages and outputs them to CHANGELOG.md.
   * It also bumps the version in `package.json` and `package-lock.json`. We don't want to
     do that just yet, but there's no way to tell standard-version to skip that step
     without breaking CHANGELOG generation. (I can provide more details on _why_ this is
     so, as needed. If you're curious, ping me directly.)
   * Note that this command adds the CHANGELOG entries under a release candidate heading,
     e.g. `### 1.3.0-rc.0`. We do not include release candidate headings in the final
     version, but we do need them for release candidate versions for two reasons: 1) They
     are convenient to refer to while the project is in its release candidate phase. 2)
     standard-version does not provide a way to generate a list of CHANGELOG entries using
     a specific range of commits or tags. It will only ever generate the list from the
     _previous tagged version_ to `HEAD`, so when it comes time to create the CHANGELOG
     for the final version, we need to already have the entries from the previous release
     candidates.
1. Get rid of the unwanted changes to `package.json` and `package-lock.json`. (I use `git
   checkout package*`)
1. Open CHANGELOG.md and review the new CHANGELOG entries to make sure they look correct.
1. Commit the new entries with the message: `chore: Update CHANGELOG for v${NEW_VERSION}`
1. Run `npm run release -- --skip.changelog --prerelease=rc`.
   * This command bumps the version in `package.json` and `package-lock.json`, commits
     them, and creates a new `v${NEW_VERSION}` tag.
1. Push the branch to a remote and open a PR/MR.
1. Once the PR/MR is reviewed and merged, push the new `v${NEW_VERSION}` tag.

#### Subsequent Release Candidates

After the initial release candidate, we may need to create more release candidates before
the final version. If the changes in the new release candidate are only fixes for features
that are in the current version, we may skip CHANGELOG generation for the sake of
simplicity, since we do not want to include CHANGELOG entries for fixes for features
introduced in the current version and follow an abbreviated process:

1. Check out a new branch, e.g. `git checkout -b prep-v1.3.0-rc.1` if the the previous
   release candidate was  `v1.3.0-rc.0`.
1. `npm run release -- --skip.changelog --prerelease=rc`
1. Push the branch and open a PR/MR.
1. Once the PR/MR is reviewed and merged, push the new `v${NEW_VERSION}` tag.

In practice, however, we sometimes add new bug fixes that should be added to the CHANGELOG
(not just bug fixes for features in the current version). When that happens, we must
follow the longer process in the "Initial Release Candidate" section again.

#### Final Version

Follow the process in the "Initial Release Candidate" section, but with these differences:

1. Omit the `--prerelease` flag from all commands
1. After generating the final CHANGELOG heading, delete the previous release candidate
   headings and merge/re-organize the entries under their appropriate "Feature", "Bug
   Fix", etc. headings. This process is described in more detail in the "Creating the
   Final Version" subheading near the end of this comment.

### Problems With the Current Process

1. When you check out the `prep-v${NEW_VERSION}` branch, you have to already know what the
   next version will be if you want to include the version in the branch name. To get the
   next version, you either have to look at the `git log` and figure it out or do a
   dry-run of an `npm release` command to see what the next version is before creating
   your branch. Or create a temporary branch name and rename the branch after the version
   bumping process is finished.
1. The command that generates the CHANGELOG also modifies package.json and
   package-lock.json before we need it and you have to manually back those changes out
   before continuing.
1. There are a number of CLI flags that you have to pass to each step and it's easy to
   forget to pass one and what they're called. It's certainly not beginner-friendly.
1. If the reviewer catches something you missed in the CHANGELOG changes, you have to
   delete the tag and version bump commit, fixup the CHANGELOG, and then re-run the 
   `npm run release -- --skip.changelog --prerelease=rc` command to regenerate the version
   bump commit and tag.
1. When creating the final version, you have to manually merge the CHANGELOG entries from
   previous release candidate versions into a single final version.
   * The reviewer will notice later that the scripts introduced in this PR _do not solve this
     problem._ Doing so would have required switching from standard-version to some other
     CLI tool, which was out of scope for this PR.

### Goals

1. Simplify the release process and commands without writing a new/complex release tool right now.
1. Allow someone to run the release process without having to be familiar with the project itself and
what entries _should_ appear in the CHANGELOG.
   * The MR that's submitted during this new process is for the CHANGELOG changes only. The MR
      should be assigned to the developer who is most familiar with the project and the changes in the
      new version.

Here is a set of instructions for adding these scripts to one of our repos, creating a
release candidate version, and creating a final version.

If this process is approved, these instructions will be the basis for another PR to the
[`silvermine-info` repo](https://github.com/silvermine/silvermine-info) to document the new release process.

## Adding These Release Scripts to a Project

1. `npm i -DE @silvermine/standardization`
2. Ensure that your `package.json` file has [a `repository.url` field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository) with the
   URL to the canonical repo for this project in your Git hosting solution, e.g.
   `https://github.com/silvermine/event-emitter.git` for the `@silvermine/event-emitter`
   project in Github.
   * This is necessary because standard-version needs to know the URL to your Git hosting
     solution so that it can make links to "compare URLs" in the CHANGELOG (e.g. the ["9.4.0" link here](https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md#940-2021-12-31)).
     standard-version looks at `package.json`'s `repository.url` field first, and then
     falls back to the `origin` git remote's URL. Until recently, we've been relying on the `origin`
     remote URL, but since we've started naming our `origin` remote `canonical` in some
     instances, standard-version can't find a URL to use. standard-version does not allow
     you to configure the name of remote it uses to get the URL. Therefore, I suggest we
     consistently use the `repository.url` field in our projects.
3. Create a symlink to: `./node_modules/@silvermine/standardization/.versionrc.js` in your
   project's root folder.
4. Add these NPM scripts to your `package.json` file:

```json
"release:prep-changelog": "./node_modules/@silvermine/standardization/release-scripts/prep-changelog.sh",
"release:finalize": "./node_modules/@silvermine/standardization/release-scripts/finalize-release.sh"
```
5. (Optional) If you are using an issue tracking system other than what your Git hosting
   solution provides (e.g. Azure DevOps instead of Github Issues), add this config to
   `package.json`:

```json
"standard-version": {
   "issueUrlFormat": "https://${YOUR_ADO_INSTANCE}/tickets/{{id}}"
}
```

### Creating a Release Candidate

   1. Check out the `master` branch (or a `release_*` branch if the release you are
      creating is not based off of `master` ). Fetch and rebase the latest changes from
      the corresponding remote branch. For example, if you are working off of master: `git
      fetch --all; git rebase origin/master`
   2. Run `npm release:prep-changelog -- --prerelease=rc`. You should now have a git
      branch called `changelog-v${NEW_VERSION}` checked out with the CHANGELOG updates
      committed.
   3. If the CHANGELOG output results in a heading with no new CHANGELOG entries, delete
      the branch and continue to step 5. Otherwise, push the branch to the correct remote
      repo, open a PR/MR, and continue with step 4.
   4. After the CHANGELOG PR/MR is reviewed and merged, fetch and rebase again so that you
      have the CHANGELOG updates in your local repo.
   5. Run `npm run release:finalize -- --prerelease=rc`. You should now have a git branch
      called `prep-v${NEW_VERSION}` checked out, with version bumps in
      package.json/package-lock.json committed along with a new tag called
      `v${NEW_VERSION}`.
   6. Push the branch to the correct remote repo and open a PR/MR.
   7. Once the PR/MR is reviewed and merged and the build pipelines finish, push the
      `v${NEW_VERSION}` tag to `origin` or `canonical`.

### Creating the Final Version

   1. Check out the `master` branch (or a `release_*` branch if the release you are
      creating is not based off of `master` ). Fetch and rebase the latest changes from
      the corresponding remote branch. For example, if you are working off of master: `git
      fetch --all; git rebase origin/master`
   2. Run `npm release:prep-changelog`. You should now have a git branch called
      `changelog-v${NEW_VERSION}` checked out with the CHANGELOG updates committed.
   3. We do not want to include individual headings for the previous release candidates in
      the final version's CHANGELOG. So, we need to remove the headings and move any
      CHANGELOG entries under them to the final version's heading. For example, consider a
      CHANGELOG that looks like this:

```md
### [1.0.0](https://${REMOTE_URL}/compare/v1.0.0-rc.1...v1.0.0) (2021-11-22)

### [1.0.0-rc.1](https://${REMOTE_URL}/compare/v1.0.0-rc.0...v1.0.0-rc.1) (2021-11-19)

### Bug Fixes

* A bugfix that we decided to add to this release ([4fff161](https://${REMOTE_URL}/commit/4fff161bee343d3caaaf74d4d576456437cfaa8f))


### [1.0.0-rc.0](https://${REMOTE_URL}/compare/v0.9.0...v1.0.0-rc.0) (2021-11-09)

### Features

* Remove flux capacitor from DeLorean ([3db39af](https://${REMOTE_URL}/commit/3db39af31ea515da9f74c0ad3f163965f41a0f59))

### Bug Fixes

* Ensure flux capacitor can reach 1.21 gigawatts when needed ([9fd45e2](https://${REMOTE_URL}/commit/9fd45e29ded483ae1b065a1bc78f5506401c20b3))
```

The headings in the CHANGELOG for the final version should look like this:

```md
### [1.0.0](https://${REMOTE_URL}/compare/v1.0.0-rc.1...v1.0.0) (2021-11-22)

### Features

* Remove flux capacitor from DeLorean ([3db39af](https://${REMOTE_URL}/commit/3db39af31ea515da9f74c0ad3f163965f41a0f59))

### Bug Fixes

* A bugfix that we decided to add to this release ([4fff161](https://${REMOTE_URL}/commit/4fff161bee343d3caaaf74d4d576456437cfaa8f))
* Ensure flux capacitor can reach 1.21 gigawatts when needed ([9fd45e2](https://${REMOTE_URL}/commit/9fd45e29ded483ae1b065a1bc78f5506401c20b3))
```

   3. Update the diff link in the final version's CHANGELOG heading so that all commits in
      the new version are included. In the example above, the CHANGELOG heading looks like
      this:

```md
### [1.0.0](https://${REMOTE_URL}/compare/v1.0.0-rc.1...v1.0.0) (2021-11-22)
```
   Note that the version range in the URL is `v1.0.0-rc.1...v1.0.0`. We want to include
   _all_ of the changes in `v1.0.0`, not just the ones since the last release candidate.
   If, for example, the last released version was `v0.9.0`, update the URL to:

```md
### [1.0.0](https://${REMOTE_URL}/compare/v0.9.0...v1.0.0) (2021-11-22)
```

   4. Push the branch to the correct remote repo and open a PR/MR.
   5. After the CHANGELOG PR/MR is reviewed and merged, fetch and rebase again so that you
      have the CHANGELOG updates in your local repo.
   6. Run `npm run release:finalize`. You should now have a commit with version bumps in
      package.json/package-lock.json along with a new tag called `v${NEW_VERSION}`.
   7. Push the changes to the branch that you are on (either `master` or a `release_*`
      branch) to the canonical remote (either `origin` or `canonical`).
   8. Push the tag to the canonical remote: `git push ${ORIGIN_OR_CANONICAL}
      v${NEW_VERSION}`

### CODE REVIEW

**Comment by yokuze** [comment]
@jthomerson could I have your concept review on these changes? I tried to give enough context for you to do so, but let me know if you have any questions.

Please note that these are `bash` scripts and will only work on macOS, Linux, or WSL.

@pbredenberg once @jthomerson is done, could I get your review on the code itself?

**Comment by onebytegone** [comment]
In talking with @pbredenberg, we might be able to simplify the release process even more. As such, I'd like to propose the changes found in #32. The full process is documented in the README changes in that PR. But in short the differences between the process described in this PR are:

1. When creating a final version, the `npm run release:prep-changelog` script will automatically remove the changelog entries for the release candidates and regenerate a single changelog for all the commits in the release. This reduces the manual editing that needs to take place to merge the headings.
   * In the event any manual edits were made to one of the RC changelog entries, these won't have been preserved in the regenerated changelog. However, the edits will still be in the git diff and should be easy enough to get back.
1. Drops the use of standard-version, but still uses conventional-changelog and friends under the hood. One of our biggest hurdles has been "standard-version doesn't allow for X". Rather than build our opinionated release tooling, working around the opinions of standard-version, it appears simpler just to use its underlying changelog/versioning libraries.
1. Will theoretically work on Windows

**Comment by yokuze** [comment]
> In talking with @pbredenberg, we might be able to simplify the release process even more. As such, I'd like to propose the changes found in #32. The full process is documented in the README changes in that PR. But in short the differences between the process described in this PR are:
> 
> 1. When creating a final version, the `npm run release:prep-changelog` script will automatically remove the changelog entries for the release candidates and regenerate a single changelog for all the commits in the release. This reduces the manual editing that needs to take place to merge the headings.
>    
>    * In the event any manual edits were made to one of the RC changelog entries, these won't have been preserved in the regenerated changelog. However, the edits will still be in the git diff and should be easy enough to get back.
> 2. Drops the use of standard-version, but still uses conventional-changelog and friends under the hood. One of our biggest hurdles has been "standard-version doesn't allow for X". Rather than build our opinionated release tooling, working around the opinions of standard-version, it appears simpler just to use its underlying changelog/versioning libraries.
> 3. Will theoretically work on Windows

Thanks for taking a look at this PR @onebytegone / @pbredenberg. About the points above:

1. It would be great not to have to manually merge the release candidate CHANGELOG entires for final versions. However, I'm a little on the fence about this change because, particularly for our highly-used libraries, we edit the CHANGELOG entries more often than not to add clarification and to fix grammar. Losing those changes and then having to re-create them from the git history every time offsets the gains from this change a bit.
1. There are a few scenarios that standard-version (and this PR) supports that #32 does not (as best I can tell). I'll describe those below.
1. Those that we work with that use Windows are already having to use WSL, which I think these scripts are compatible with.

From what I can tell (please correct me if I'm wrong), #32 doesn't support a few scenarios that this PR does (and that we've had using `standard-version` directly until now):

1. **alpha/beta prerelease tags** (or any tag other than `rc`) - It looks like #32 assumes that we will only ever use an `rc` release tag. We've used `alpha` and `beta` in the past to publish versions that aren't ready for a full release candidate bump: https://github.com/silvermine/eslint-config-silvermine/releases/tag/v3.1.0-beta.0 How would we support those? 
1. **Overriding the auto-calculated version** - There are two scenarios where we need to be able to specify the version number that we want to publish instead of letting our release script calculate the version. We do this using standard-version's [`--release-as` flag](https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like).
   1. When performing a major version bump (e.g. `1.2.1` to `2.0.0`). It's been difficult for developers to consistently use the `BREAKING CHANGE:` tag in a commit message footer so that `conventional-*` calculates a major version bump instead of a minor one. It's easy to forget, and sometimes there's not a single commit to point to as a "breaking change" but rather a series of commits that implement a breaking change. So, we almost always have to tell `standard-release` to override its calculated version with a major version bump.
   3. Developers sometimes use conventional-commit tags incorrectly. A handful of times developers have used `feat` when they should've used `fix`, `refactor`, `docs`, or `ci`. When it slips past code review and ends up in `master`, the release scripts will auto-calculate the wrong version and we need to be able to override it. True, we should strive not to do this and train others to use commit tags correctly, but our release process should realistically acknowledge that we will make mistakes and allow us to correct them.
   4. [Breaking changes are acceptable between `0.x` versions](https://semver.org/#spec-item-4), but the script in #32 bumps to `v1.x` when a commit includes the `BREAKING CHANGE` tag. Let's say that we are on `v0.8.0`, create a breaking change in the API and use the `BREAKING CHANGE` tag but want the next version to be `v0.9.0` because we are not ready for a `v1.0.0` yet. `standard-version` accounts for this scenario and bumps you to `v0.9.0` (you supply the `--release-as` flag to take it to a `v1.0.0` when you're ready).
 
Minor issues:

1. **We lose the ability to skip version bumping for the first release** - `standard-version` has a [`--first-release` flag](https://github.com/conventional-changelog/standard-version#first-release) that we use when generating the CHANGELOG and tag for the first release. That flag skips the version bump when performing the initial release because we usually don't want to bump the version in package.json for the first release.
2. **We lose the ability to do dry-runs** - `standard-version` has a [`--dry-run` flag](https://github.com/conventional-changelog/standard-version#dry-run-mode) that you can use to check the results of a command without actually performing the command. This is useful when you want to preview what the next version number will be without actually updating the changelog/committing. For example, if you _know_ that the next version should be a major version bump but you'd rather not scroll through the list of commits to check whether or not the developers included the `BREAKING CHANGE` footer tag, you can just run the CHANGELOG generation command with the `--dry-run` flag to understand what version you're going to get.

Overall, I think the logging output and programming language is better in #32. However, while `standard-version` isn't ideal for our use case, ultimately I stuck with it in this PR because:
1. The flexibility it offers accounts for these scenarios
2. Overall it's fewer LOC than stitching together different libs ourselves

Perhaps there's a way to adjust #32 so that we can at least support the first two "must-haves"? Or would it be simpler to stick with `standard-version` and this PR? What do @onebytegone and @pbredenberg think about these points and use cases?

**Comment by onebytegone** [comment]
Great notes @yokuze! It's good we're finally getting the requirements documented. I think most of the changes noted are simple to resolve. The changes have been pushed to #32. Comments inline.
 
> 1. It would be great not to have to manually merge the release candidate CHANGELOG entries for final versions. However, I'm a little on the fence about this change because, particularly for our highly-used libraries, we edit the CHANGELOG entries more often than not to add clarification and to fix grammar. Losing those changes and then having to re-create them from the git history every time offsets the gains from this change a bit.

In my testing, pulling back the manual edits for these cases is basically:

```bash
npm run release:prep-changelog
git reset HEAD^
git add -p # and stage the changes you want
git commit -m "chore: update changelog for v1.0.0"
```

As example based on your prior example, the RC-based changelog of:

```
## [1.0.0-rc.2](https://github.com/onebytegone/package-versioning-test-repo/compare/v1.0.0-rc.1...v1.0.0-rc.2) (2022-03-02)


### Features

* install Mr. Fusion ([9370f17](https://github.com/onebytegone/package-versioning-test-repo/commit/9370f171554ef0b3c4d07aebfa294432102af3ab))


### Bug Fixes

* walk past the almanac ([992a4c7](https://github.com/onebytegone/package-versioning-test-repo/commit/992a4c742ac1af3a58cf182308327a743de2ad35))


## [1.0.0-rc.1](https://github.com/onebytegone/package-versioning-test-repo/compare/v1.0.0-rc.0...v1.0.0-rc.1) (2022-03-02)


### Bug Fixes

* remove need for roads ([09d3174](https://github.com/onebytegone/package-versioning-test-repo/commit/09d317461f246a291844f964418067fdcfa99ff9))


## [1.0.0-rc.0](https://github.com/onebytegone/package-versioning-test-repo/compare/v0.1.0...v1.0.0-rc.0) (2022-03-02)


### Features

* add flux capacitor to the DeLorean OUTATIME ([6adb1f9](https://github.com/onebytegone/package-versioning-test-repo/commit/6adb1f9eb28c32eae4407eda222ffeb0f8cc7263))
   * If you're gonna build a time machine into a car, why not do it with some style?

### Bug Fixes

* ensure flux capacitor can reach 1.21 gigawatts when needed ([8e1c5f6](https://github.com/onebytegone/package-versioning-test-repo/commit/8e1c5f6ea7fc3fcd70f9373e0a000772526e4b63))
   * ONE POINT TWENTY-ONE GIGAWATTS!!!
```
 
will be regenerated and committed as:

```diff 
@@ -3,39 +3,20 @@
 All notable changes to this project will be documented in this file.
 See [our coding standards][commit-messages] for commit guidelines.

-## [1.0.0-rc.2](https://github.com/onebytegone/package-versioning-test-repo/compare/v1.0.0-rc.1...v1.0.0-rc.2) (2022-03-02)
+## [1.0.0](https://github.com/onebytegone/package-versioning-test-repo/compare/v0.1.0...v1.0.0) (2022-03-02)


 ### Features

+* add flux capacitor to DeLorean ([6adb1f9](https://github.com/onebytegone/package-versioning-test-repo/commit/6adb1f9eb28c32eae4407eda222ffeb0f8cc7263))
 * install Mr. Fusion ([9370f17](https://github.com/onebytegone/package-versioning-test-repo/commit/9370f171554ef0b3c4d07aebfa294432102af3ab))


-### Bug Fixes
-
-* walk past the almanac ([992a4c7](https://github.com/onebytegone/package-versioning-test-repo/commit/992a4c742ac1af3a58cf182308327a743de2ad35))
-
-
-## [1.0.0-rc.1](https://github.com/onebytegone/package-versioning-test-repo/compare/v1.0.0-rc.0...v1.0.0-rc.1) (2022-03-02)
-
-
-### Bug Fixes
-
-* remove need for roads ([09d3174](https://github.com/onebytegone/package-versioning-test-repo/commit/09d317461f246a291844f964418067fdcfa99ff9))
-
-
-## [1.0.0-rc.0](https://github.com/onebytegone/package-versioning-test-repo/compare/v0.1.0...v1.0.0-rc.0) (2022-03-02)
-
-
-### Features
-
-* add flux capacitor to the DeLorean OUTATIME ([6adb1f9](https://github.com/onebytegone/package-versioning-test-repo/commit/6adb1f9eb28c32eae4407eda222ffeb0f8cc7263))
-   * If you're gonna build a time machine into a car, why not do it with some style?
-
 ### Bug Fixes

 * ensure flux capacitor can reach 1.21 gigawatts when needed ([8e1c5f6](https://github.com/onebytegone/package-versioning-test-repo/commit/8e1c5f6ea7fc3fcd70f9373e0a000772526e4b63))
-   * ONE POINT TWENTY-ONE GIGAWATTS!!!
+* remove need for roads ([09d3174](https://github.com/onebytegone/package-versioning-test-repo/commit/09d317461f246a291844f964418067fdcfa99ff9))
+* walk past the almanac ([992a4c7](https://github.com/onebytegone/package-versioning-test-repo/commit/992a4c742ac1af3a58cf182308327a743de2ad35))
```

After resetting that commit, it's just a process of picking the changes that you want to keep (i.e. dropping mention of the almanac, it never happened).

```diff
 @@ -3,39 +3,20 @@
 All notable changes to this project will be documented in this file.
 See [our coding standards][commit-messages] for commit guidelines.

-## [1.0.0-rc.2](https://github.com/onebytegone/package-versioning-test-repo/compare/v1.0.0-rc.1...v1.0.0-rc.2) (2022-03-02)
-
-
-### Features
-
-* install Mr. Fusion ([9370f17](https://github.com/onebytegone/package-versioning-test-repo/commit/9370f171554ef0b3c4d07aebfa294432102af3ab))
-
-
-### Bug Fixes
-
-* walk past the almanac ([992a4c7](https://github.com/onebytegone/package-versioning-test-repo/commit/992a4c742ac1af3a58cf182308327a743de2ad35))
-
-
-## [1.0.0-rc.1](https://github.com/onebytegone/package-versioning-test-repo/compare/v1.0.0-rc.0...v1.0.0-rc.1) (2022-03-02)
-
-
-### Bug Fixes
-
-* remove need for roads ([09d3174](https://github.com/onebytegone/package-versioning-test-repo/commit/09d317461f246a291844f964418067fdcfa99ff9))
-
-
-## [1.0.0-rc.0](https://github.com/onebytegone/package-versioning-test-repo/compare/v0.1.0...v1.0.0-rc.0) (2022-03-02)
+## [1.0.0](https://github.com/onebytegone/package-versioning-test-repo/compare/v0.1.0...v1.0.0) (2022-03-02)


 ### Features

 * add flux capacitor to the DeLorean OUTATIME ([6adb1f9](https://github.com/onebytegone/package-versioning-test-repo/commit/6adb1f9eb28c32eae4407eda222ffeb0f8cc7263)
    * If you're gonna build a time machine into a car, why not do it with some style?
+* install Mr. Fusion ([9370f17](https://github.com/onebytegone/package-versioning-test-repo/commit/9370f171554ef0b3c4d07aebfa294432102af3ab))

 ### Bug Fixes

 * ensure flux capacitor can reach 1.21 gigawatts when needed ([8e1c5f6](https://github.com/onebytegone/package-versioning-test-repo/commit/8e1c5f6ea7fc3fcd70f9373e0a
    * ONE POINT TWENTY-ONE GIGAWATTS!!!
+* remove need for roads ([09d3174](https://github.com/onebytegone/package-versioning-test-repo/commit/09d317461f246a291844f964418067fdcfa99ff9))
```

Worse comes to worse, the releaser can manually update the changelog [as described earlier](https://github.com/silvermine/standardization/pull/28#issue-1060537976). However, I think the number of repos that we manually the edit the changelog for is far surpassed by those we don't need to edit. I'd rather have the default cover the 80% case for changelog generation.

> 1. **alpha/beta prerelease tags** (or any tag other than `rc`) - It looks like [feat: add script to simplify the package release process (#27) #32](https://github.com/silvermine/standardization/pull/32) assumes that we will only ever use an `rc` release tag. We've used `alpha` and `beta` in the past to publish versions that aren't ready for a full release candidate bump: https://github.com/silvermine/eslint-config-silvermine/releases/tag/v3.1.0-beta.0 How would we support those?

Yeah, @pbredenberg and I didn't have this requirement in our notes. On #32, the `--rc` flag has been replaced with `--prerelease rc`. Wanted to keep the interface simple, but it doesn't seem possible to get around this one.

> 2. **Overriding the auto-calculated version** - There are three scenarios where we need to be able to specify the version number that we want to publish instead of letting our release script calculate the version. We do this using standard-version's [`--release-as` flag](https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like).
>    
>    1. When performing a major version bump (e.g. `1.2.1` to `2.0.0`). It's been difficult for developers to consistently use the `BREAKING CHANGE:` tag in a commit message footer so that `conventional-*` calculates a major version bump instead of a minor one. It's easy to forget, and sometimes there's not a single commit to point to as a "breaking change" but rather a series of commits that implement a breaking change. So, we almost always have to tell `standard-release` to override its calculated version with a major version bump.
>    2. Developers sometimes use conventional-commit tags incorrectly. A handful of times developers have used `feat` when they should've used `fix`, `refactor`, `docs`, or `ci`. When it slips past code review and ends up in `master`, the release scripts will auto-calculate the wrong version and we need to be able to override it. True, we should strive not to do this and train others to use commit tags correctly, but our release process should realistically acknowledge that we will make mistakes and allow us to correct them.

These has been remedied by adding a `--version <version>` option.

>    3. [Breaking changes are acceptable between `0.x` versions](https://semver.org/#spec-item-4), but the script in [feat: add script to simplify the package release process (#27) #32](https://github.com/silvermine/standardization/pull/32) bumps to `v1.x` when a commit includes the `BREAKING CHANGE` tag. Let's say that we are on `v0.8.0`, create a breaking change in the API and use the `BREAKING CHANGE` tag but want the next version to be `v0.9.0` because we are not ready for a `v1.0.0` yet. `standard-version` accounts for this scenario and bumps you to `v0.9.0` (you supply the `--release-as` flag to take it to a `v1.0.0` when you're ready).

There's a [`preMajor` flag on conventional-recommended-bump](https://github.com/conventional-changelog/conventional-changelog/blob/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/conventional-recommended-bump/test/index.spec.js#L269-L282) that made this simple enough to fix.

> 1. **We lose the ability to skip version bumping for the first release** - `standard-version` has a [`--first-release` flag](https://github.com/conventional-changelog/standard-version#first-release) that we use when generating the CHANGELOG and tag for the first release. That flag skips the version bump when performing the initial release because we usually don't want to bump the version in package.json for the first release.

With the `--version <version>` option, it's now possible to run `npm run release:prep-changelog -- --version 0.1.0` and  `npm run release:finalize -- --version 0.1.0` for this case.

> 2. **We lose the ability to do dry-runs** - `standard-version` has a [`--dry-run` flag](https://github.com/conventional-changelog/standard-version#dry-run-mode) that you can use to check the results of a command without actually performing the command. This is useful when you want to preview what the next version number will be without actually updating the changelog/committing. For example, if you _know_ that the next version should be a major version bump but you'd rather not scroll through the list of commits to check whether or not the developers included the `BREAKING CHANGE` footer tag, you can just run the CHANGELOG generation command with the `--dry-run` flag to understand what version you're going to get.

Added `npm run release:preview`. This also makes it so developers can see what their commits will do to the changelog and version if they want.

> Overall, I think the logging output and programming language is better in #32. However, while `standard-version` isn't ideal for our use case, ultimately I stuck with it in this PR because:
> 
> 1. The flexibility it offers accounts for these scenarios
> 2. Overall it's fewer LOC than stitching together different libs ourselves

I don't like the increase in LoC either. However, I think it's worth the cost.

   1. Our goal has been to make releases less painful. The cost is ~300 lines of "glue" and logging code to remove most of the pain points. Based on other scripts of a similar nature and size, I don't expect there to be a large maintenance cost.
   2. Does what we need and no more. `standard-version` can do a lot of things, but knowing which we need isn't always clear (as we've found in the many conversations about releases that the team's had 😆 ).
   3. Clarifies what lib is doing what part of the process. We've long run into the issue "what's doing this part of the release process?" There's value in having one layer of abstraction removed.

**Comment by yokuze** [comment]
Closed in favor of #32

**Pull request closed without merging**
